### ISSUE TITLE
quite a few links are broken

### ISSUE THREAD

**Issue by littleidea** [openservicebrokerapi/servicebroker#133] opened 2017-02-01 20:52 UTC
looks like there are missing docs

These are all links on https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md that 404 on github for me (basically any link that isn't self referencing spec.md):
https://github.com/openservicebrokerapi/servicebroker/blob/devguide/services/index.html
https://github.com/openservicebrokerapi/servicebroker/blob/master/v2-api-changelog.md
https://github.com/openservicebrokerapi/servicebroker/blob/master/app-log-streaming.md
https://github.com/openservicebrokerapi/servicebroker/blob/master/route-services.md
https://github.com/openservicebrokerapi/servicebroker/blob/master/volume-services.md
https://github.com/openservicebrokerapi/servicebroker/blob/master/catalog-metadata.md
https://github.com/openservicebrokerapi/servicebroker/blob/master/dashboard-sso.md
https://github.com/openservicebrokerapi/servicebroker/blob/master/managing-service-brokers.md#register-broker
https://github.com/openservicebrokerapi/servicebroker/blob/master/api.md#broker-errors
https://github.com/openservicebrokerapi/servicebroker/blob/master/examples.md
https://github.com/openservicebrokerapi/servicebroker/blob/devguide/services/managing-services.html#update_service

this is a 404 on cloudfoundry.org
http://docs.cloudfoundry.org/running/managing-cf/quota-plans.md

I only made it about 20% though spec.md before creating this issue, but it looks like the supporting docs might not have been migrated.

**Comment by angarg12** [comment] 2017-02-02 07:37
This is a duplicate of #120, and will be fixed by #131.

**Closed by angarg12** 2017-02-02 07:37 UTC
Labels: bug, duplicate, wontfix
