### ISSUE TITLE
Short/Long Description Fields should also specify valid Character lengths

### ISSUE THREAD

**Issue by codevulture** [openservicebrokerapi/servicebroker#509] opened 2018-04-23 07:51 UTC
Description fields with names short and long makes sense but there should also be specified guidelines for how much character lengths are permitted in short/long for better understanding/Usage.

At various places descriptions are present like: https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#request

**Comment by jmrodri** [comment] 2018-04-24 16:05
The only thing I don't like about specifying character lengths is that each platform / broker can define what is short and long for them. Was there a specific problem that you encountered that required knowing the specific lengths?

**Comment by mattmcneeney** [comment] 2018-04-26 10:31
Platforms and tooling will likely have very different lower and upper limits for strings (depending on the database they use for example). We could try to specify a minimum length that must be supported, but in reality, it's very unlikely that an engineer working on a UI for a platform would ever come to this repository looking for what that limit is. So I'm not sure we would gain much from this change. I'd be up for adding some guidance to the spec though, such as `Note that different Platforms and other tooling may have different limitations on how the information contained in the catalog can be displayed, so care should be taken to ensure all strings are of a sensible length.`

**Comment by codevulture** [comment] 2018-05-02 04:55
@mattmcneeney : thanks. But again `sensible length` is something which could mean anything :) , I think we can close the bug if this is upto the platform but i was hoping we specify something like short desc should not be more than say 1000 chars . Please let me know your opinion.

**Comment by mattmcneeney** [comment] 2018-05-02 12:06
It fundamentally is up to the Platform, but I agree that at least adding a recommended max to the spec will hopefully encourage Platform authors to at least support that size. Thoughts @duglin ?

**Comment by bingosummer** [comment] 2018-05-03 23:56
We find, if the plan description is more than 255 characters, we can't create the service broker. CF CLI will throw an error.
```
FAILED
Server error, status code: 500, error code: 10011, message: Database error
```
From cloud_controller_ng.log in the `api` VM, we can get the error:
```
cloud_controller_ng.log:{"timestamp":1525390599.173751,"message":"Request failed: 500: {\"description\"=>\"Database error\", \"error_code\"=>\"CF-DatabaseError\", \"code\"=>10011, \"test_mode_info\"=>{\"description\"=>\"Database error\", \"error_code\"=>\"CF-DatabaseError\", \"backtrace\"=>[\"/var/vcap/data/packages/cloud_controller_ng/62c8af07f22f0a55027a434635d798e794392097/cloud_controller_ng/app/controllers/base/base_controller.rb:85:in `rescue in dispatch'\", \"/var/vcap/data/packages/cloud_controller_ng/62c8af07f22f0a55027a434635d798e794392097/cloud_controller_ng/app/controllers/base/base_controller.rb:77:in `dispatch'\", \"/var/vcap/data/packages/cloud_controller_ng/62c8af07f22f0a55027a434635d798e794392097/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1610:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1610:in `block in compile!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/nulllogger.rb:9:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/request_logs.rb:22:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/security_context_setter.rb:19:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/vcap_request_id.rb:15:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/cors.rb:49:in `call_app'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/cors.rb:14:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/request_metrics.rb:12:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/builder.rb:153:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:50:in `block in process'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'\"]}}","log_level":"error","source":"cc.api","data":{"request_guid":"e885c250-bf6b-4108-7a19-007e31f7d2a8::ac2c8ed7-eeee-4e7d-ad03-cd6aa3825326"},"thread_id":46968796863000,"fiber_id":46968813265360,"process_id":19682,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/sinatra/vcap.rb","lineno":46,"method":"block in registered"}
```

Unfortunately, it's hard to find the root cause. After several test, we believe, up to 255 characters are allowed for the plan description.

1. I think, it's valuable to document the max length for different platform.
2. If the cloud controller can provide a more meaningful error message, that would be good. I will open an issue in cloud controller too.

**Comment by Samze** [comment] 2018-05-04 13:54
CloudController does have a 255 character limit on service and plan descriptions. The description is output on the CLI and to UI clients and so to provide a better UX for consumers a 255 limit was chosen. 

@bingosummer Totally agree that the error message is rubbish - we will take a look at the issue you raised, thanks!

Without any guidance in the spec we are expecting broker authors to either read through all platform documentation or guess. Neither of these seem like ideal options.

In the spirit of the open part of the OSBAPI it would be great if broker authors could get some guarantee from the spec. I would be in favour of a documenting a size that platforms must at least support. That way broker authors know that if they want their broker to work X-platform they must keep within that limit and if they go above that then they must look at individual platform support.

**Comment by duglin** [comment] 2018-05-08 11:53
ug - these types of issues are ugly :-)

I can see someone complaining about this in both directions... ie. they wanted to add more text to their "short" description because one platform lets them but some other platform doesn't - so that implies we should define the upper limit in the spec to force interop. Yet @mattmcneeney suggested a lower limit, I think... that text could be read more than one way.

I'm not sure we can mandate anything right now w/o breaking backwards compatibility. But, if we wanted to put in some guidance in prep for v3 then I'd be ok with picking a max for short descriptions (meaning impls MUST a string of any length up to max). What about long descriptions? Leave them wide open or pick a max for those too? 4096?  Keep in mind, no matter what values we pick someone will probably complain :-)

**Comment by mattmcneeney** [comment] 2018-05-08 12:00
If we want to add guidance in V2, what about something very simple like:
`Platforms MAY have limits on the length of strings that they display to end users, such as the description of a Service or Service Plan. It is RECOMMENDED that strings do not exceed 255 characters to increase the likelihood of having compatibility with any Platform.`

**Comment by mattmcneeney** [comment] 2018-05-09 12:50
On the call last night, there were no objections to adding some text to the spec similar to what I outlined above. What do you all think? Happy for me to submit a PR?

**Comment by mattmcneeney** [comment] 2018-05-10 14:01
@duglin Recommendation is for strings up to 255 characters in length across the spec.

**Comment by codevulture** [comment] 2018-05-11 01:42
@mattmcneeney : thanks for your efforts, one more question 255 would make sense for short desc but i think for long desc, limit should be slightly higher? What do you think?

**Comment by mattmcneeney** [comment] 2018-05-11 15:55
Which fields are you interested in adding more than 255 characters too? I'd be hesitant to recommend any longer fields unless we can be confident that the tooling (UIs and CLIs) work well with longer strings.

**Comment by codevulture** [comment] 2018-05-12 04:12
@mattmcneeney :+1:  Thanks!

**Comment by n3wscott** [comment] 2018-05-14 16:19
Adding limits to the spec would be a breaking change. If the platform is unable to store the data then it should truncate it to protect itself.

**Comment by mattmcneeney** [comment] 2018-05-15 09:34
@n3wscott We're not planning on adding a limit to the spec, just a recommendation to service authors who want to ensure 'best' compatibility with platform UXs.

**Comment by mattmcneeney** [comment] 2019-06-24 13:05
Closing this after adding guidance for supported string lengths.

**Closed by mattmcneeney** 2019-06-24 13:05 UTC
